### ISSUE TITLE
Cant locate LibreOffice in cygwin

### ISSUE THREAD

**Issue by trufanov-nok** [dagwieers/unoconv#256] opened 2015-05-26 10:30 UTC
Hi,
I've installed current LibreOffice. It's accessible underCygwin: `/cygdrive/c/Program Files (x86)/LibreOffice 4`   
Unfortunately, unoconv doesn't see it:
```
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues
```

How can I fix this problem?

**Comment by skywinder** [comment] 2015-05-26 11:48
Duplicate of #252

Use `brew install unoconv --HEAD` until the new version is not released

(I'm waiting approve of @dagwieers to release new version)

**Closed** 2015-06-23 07:10 UTC
Labels: duplicate
