### ISSUE TITLE
problem pdf to doc convert

### ISSUE THREAD

**Issue by cleobatista** [dagwieers/unoconv#352] opened 2016-08-10 00:02 UTC
cleo@cleo:~$ unoconv -vvv -f doc Downloads/danfe.pdf 
Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002;urp;StarOffice.ComponentContext
Input file: Downloads/danfe.pdf
Selected output format: Microsoft Word 97/2000/XP [.doc]
Selected office filter: MS Word 97
Used doctype: document
Output file: Downloads/danfe.doc
Traceback (most recent call last):
  File "/usr/local/bin/unoconv", line 933, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.IOException: SfxBaseModel::impl_store file:///home/cleo/Downloads/danfe.doc failed: 0xc10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/unoconv", line 1169, in <module>
    main()
  File "/usr/local/bin/unoconv", line 1088, in main
    convertor.convert(inputfn)
  File "/usr/local/bin/unoconv", line 935, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/usr/lib/python3/dist-packages/uno.py", line 397, in _uno_struct__getattr__
    return **builtin**.getattr(self.**dict**["value"],name)
AttributeError: ErrCode

**Comment by feixhan** [comment] 2016-09-04 08:02
I have the same error。
libreoffice5.2
unoconv:GitHub master branch.
Run unoconv with root.

**Comment by xq5he** [comment] 2016-10-24 03:45
`lsof -i:2002`
`kill {pid}`

**Comment by tareqtms** [comment] 2018-09-11 05:03
Having the same issue. No solutions?

**Comment by regebro** [comment] 2019-02-28 13:04
Duplicate of #279

**Closed by regebro** 2019-02-28 13:04 UTC
