### ISSUE TITLE
problem in converting documents to pdf with argument "--stdout" (ErrCode 3088)

### ISSUE THREAD

**Issue by abbshr** [dagwieers/unoconv#220] opened 2014-09-11 08:35 UTC
I want the output stream from unoconv, but when I run `unoconv -f pdf --stdout xxx.doc`,it show these, and don't know what that "error 3088" means :

```
unoconv: UnoException during export phase:
Unable to store document to private:stream (ErrCode 3088)

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"writer_pdf_Export" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x950bd84{, supportedInterfaces={com.sun.star.lang.XTypeProvider,com.sun.star.io.XOutputStream}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })
```

platform: ubuntu 13.10 i686

**Comment by dagwieers** [comment] 2015-07-04 23:26
Can you check the latest version from the master branch ?
There was an issue with the python3 implementation and I reverted the change.

Thanks in advance !

**Comment by dagwieers** [comment] 2015-07-05 11:42
Well, just as a reference, ErrCode 3088 means:

Binary: 000:01100:00010000
 - Area: 0 (ERRCODE_AREA_TOOLS)
 - Class: 12 (ERRCODE_CLASS_WRITE)
 - Code: 16 (ERRCODE_IO_CANTWRITE)

I could be wrong, but it feels as if this is a permission/ACL/SELinux related problem.
Is that possible ?

**Comment by dagwieers** [comment] 2015-07-05 17:46
Ok, I am going to close this because I am confident that is fixed.
If you still experience this issue with the latest version from the master branch, feel free to reopen this ticket with the information to reproduce it and you'll get my full attention again :-)

Thanks for the feedback !

**Closed by dagwieers** 2015-07-05 17:46 UTC
Labels: feedback, support
