### ISSUE TITLE
sudo -u www unoconv -f pdf 1.ppt  erro   help me!!

### ISSUE THREAD

**Issue by aimchina** [dagwieers/unoconv#259] opened 2015-06-08 12:43 UTC
I use  "sudo -u root unoconv -f pdf 1.ppt" , it's can do it. 

but I use "sudo -u www unoconv -f pdf 1.ppt"    then erro:

unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: Error during bootstrapping uno (RuntimeException):cannot open file:///root/.ure/types.rdb

why?   anybody help me?

**Comment by aimchina** [comment] 2015-06-08 13:24
root@AY140612212250787b5cZ:/alidata/hd# sudo -u www unoconv -f pdf 1.ppt
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: Error during bootstrapping uno (RuntimeException):cannot open file:///root/.ure/types.rdb

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1170, in <module>
    main()
  File "/usr/bin/unoconv", line 1087, in main
    convertor = Convertor()
  File "/usr/bin/unoconv", line 733, in __init__
    product = self.svcmgr.createInstance("com.sun.star.configuration.ConfigurationProvider").createInstanceWithArguments("com.sun.star.configuration.ConfigurationAccess", UnoProps(nodepath="/org.openoffice.Setup/Product"))
uno.RuntimeException: cannot open directory file:///root/.openoffice/4/user/uno_packages/cache/registry/com.sun.star.comp.deployment.configuration.PackageRegistryBackend/registry

**Comment by skywinder** [comment] 2015-06-23 07:29
Please, specify OS, and version of unoconv and LibreOffice.

**Comment by dagwieers** [comment] 2015-06-23 08:44
What is already weird is that for user "www" it somwhere has a reference to */root*. (e.g. */root/.ure* and */root/.openeoffice*)

So the first question should be, why would user "www" try to access files in */root* ?
Maybe try running something like: `sudo -u www env`

**Comment by dagwieers** [comment] 2015-07-05 10:06
Ok, this is a known issue. The cause is related to user "www" not having a correct `PATH` set, or not having a correct `HOME` set. We are looking into fixing this from within unoconv, or allowing the user to provide its own `PATH` environment variable.

**Comment by dagwieers** [comment] 2015-07-05 10:45
We are tracking related issues in the thread of issue #87.
For that reason I am closing this issue.

If you still think this is a different issue, feel free to reopen this issue and provide ample evidence to reproduce the problem. Thanks for your feedback !

**Closed by dagwieers** 2015-07-05 10:45 UTC
Labels: support
