### ISSUE TITLE
UNO IllegalArgument during import phase: Source file cannot be read.

### ISSUE THREAD

**Issue by menson** [dagwieers/unoconv#160] opened 2013-08-17 09:18 UTC
hi!
unoconv -f pdf test.doc
UNO IllegalArgument during import phase:
Source file cannot be read. Unsupported URL <file:///tmp/test.doc>: ""

unoconv --version
unoconv 0.6
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux2
python 2.7.3 (default, Apr 10 2013, 06:20:15)
[GCC 4.6.3]
LibreOffice 3.5

os:ubuntu

**Comment by ciropom** [comment] 2015-01-13 09:31
I also got an error like this one, and I found out that's because the filename contained an utf-8 char..
unoconv -f pdf /..../cicciò.doc
unoconv: file `/.../cicci .doc' does not exist.
UNO IllegalArgument during import phase:
Source file cannot be read. Unsupported URL <file:///cicci%20.doc>: ""

**Comment by dagwieers** [comment] 2015-07-05 11:32
I cannot reproduct this on my Linux system.
```bash
[dag@moria unoconv]$ /opt/libreoffice5.0/program/python unoconv -v -f pdf cicciò.fodt 
Input file: cicciò.fodt
Selected output format: Portable Document Format [.pdf]
Output file: file:///home/dag/home-made/unoconv/cicci%C3%B2.pdf
[dag@moria unoconv]$ /opt/libreoffice3.5/program/python unoconv -v -f pdf cicciò.fodt 
Input file: cicciò.fodt
Selected output format: Portable Document Format [.pdf]
Output file: file:///home/dag/home-made/unoconv/cicci%C3%B2.pdf
```

Not even with LibreOffice 3.5, so either this is fixed, or this is an OS-specific issue.
Can you try again with the latest master branch and a recent LibreOffice ?

Thanks in advance !

**Comment by dagwieers** [comment] 2015-07-05 21:48
I am going to close this. If this is still giving you problems with a recent unoconv and LibreOffice, feel free to reopen this issue and provide us with the details to reproduce this issue.

Thanks for the feedback !

**Closed by dagwieers** 2015-07-05 21:48 UTC
Labels: feedback, support
